### ISSUE TITLE
var=$(cmd args) doesn't need quotes

### ISSUE THREAD

**Issue by froh** [lhunath/guide.bash.academy#88]
please remove the double quotes here

https://github.com/lhunath/guide.bash.academy/blob/1ec01466a62a66d69b2446c9a8d4cd6cebdffdfa/expansions.html#L329

example:

```bash
X=$(ls) # no quotes needed here
echo $X # word splitting happens here
echo "$X" # see: embedded newlines...
```

**Comment by lhunath** [comment]
You are correct that double quotes around the expansion in this example are superfluous.

Regardless, the rationale in using them is not strictly limited to cases where their absence would lead to problems. Such a rationale can easily devolve in arguments such as "don't use double quotes when you know the value will not contain white-space", or "don't use double quotes when you know `IFS` is safe", etc.

In practice, I aim to provide safe habits that will help a less sophisticated reader to automatically do the right thing in most cases. If we start omitting quotes in places, we are subconsciously teaching the reader that it is OK sometimes to omit the quotes, despite the reader not having the skills to apply that lesson effectively, increasing the risk of the lesson becoming more harmful than helpful. That's quite easy to do in this case since omitting the quotes is a no-op, making it 0 helpful (or 0.00001 for saving 2 bytes of disk space and keyboard effort).

Thank you for the suggestion! I hope my explanation was helpful, perhaps not convincing, but at least to understand why I won't proceed.

**Comment by froh** [comment]
thanks for the detailed response.

here is why I beg to reconsider

```bash
X=$(ls "*   *") # the glob contains three spaces, delieberately so..
Y="$(ls \"*   *\")" # now you find yourself quoting quotes ...
Z="$(ls '*   *')" # ... or using different quote characters
```

I think we agree quoting in the shell is "a mess".

The major source of confusion, I think we also agree, is dealing with filenames with embedded $IFS characters or shell builtin token separators.

and the major use case where this matters is building and collecting command lines for other commands.

and to that end in my experience with colleagues less versed in the fine points and nuances, the following guidance has proven most useful:

* if you use a variable containing a single file/dirname/"$PATH", with the intended meaning: "insert the contents of this variable here and do what I mean", then wrap it in double quotes: "${foo}"
* if you use an array, wrap it in double quotes
* if you need to collect a number of arguments in one variable, use bash arrays
* wrap all variable uses in curly braces.  yes, they are only _needed_ if the variable name is followed by \[:alnum:] or _, however those who touch the script after you may not know that nuance yet.  and array expansion _always_ needs it.
* don't use eval

for example:
 
```bash
fooARGS=(ah -blah "eh spah"/*njol) # an array of three arguments
barARGS=($(ls -1 "${murghdir}/*  *")) # gather the output of a command in an array
cmd="${cmddir}/da_cmd"

"${cmd}" foo "${fooARGS[@]}" --bar "${barARGS[@]}"
```

this gets rid of all nested, quoted quotes, it gets rid of the need for single quotes for most uses, it simplifies things for beginners.  and it's beginners who maintain the scripts later and add an argument or change the argument list or whathaveyou.

anyhow, I very much appreciate the work you put into this and I like it, very much, either way :-)

**Comment by lhunath** [comment]
Hi and thank you for expanding on your thoughts!

I am largely in agreement with your suite of recommendations, although you have one slip-up, which goes to the core of the argument. It is true that in POSIX sh, with back-tick expansion, we are forced to write this:

```
Y="`ls \"*   *\"`" # now you find yourself quoting quotes ...
```
however, this is the beauty of bash's `$()` syntax: it treats quotes as self-contained, ergo, the above is equivalent to:
```
Y="$(ls "*   *")"
```
no escaping of quotes is necessary. In fact, you'll find that if you do escape the quotes, you render them disabled, and you'll be resolving 2 arguments to `ls`, one that searches for all files starting with a double-quote character, and another that searches for all files ending with a double-quote character - not likely your intention.

I would certainly agree with you were we under POSIX sh, but the chaos is inescapable (no pun intended) in POSIX sh, since the escaping becomes unavoidable eg. when expanding inside the expansion (<code>Y=\`foo \\"\`bar\`\\"\`</code>).
But in Bash, we can safely quote all expansions with no need for any forethought.

I would prefer not to render a situation where the uninitiated needs to think really hard about which of these four cases minimally require the expansion to be quoted and which of them do not, and simply recommend them to quote all, no harm done:
```
FOO=$(bar)
FOO=$(bar) quux
env FOO=$(bar) quux
quux --FOO=$(bar)
```

**Comment by froh** [comment]
ok I see.  and I now follow your train of thought for a beginner guide...

the `FOO=$(bar)` made it's value click for me, and I have to admit, I wasn't aware of `"$(echo "<   >")"`, i.e. the full nesting effect of `$()`.

🙄 oh well.  and thanks again :-)
